export async function loader() {
  const leaves = await [
    {
      id: 1,
      employeeId: "EMP-003",
      name: "Su Su Win",
      department: "Finance",
      role: "Accountant",
      type: "Annual Leave",
      startDate: "2026-04-25",
      endDate: "2026-04-29",
      duration: 5,
      reason: "Family trip planned during the public holiday stretch.",
      status: "Approved",
      approver: "Finance Director",
    },
    {
      id: 2,
      employeeId: "EMP-014",
      name: "Cherry Myint",
      department: "HR",
      role: "Recruiter",
      type: "Medical Leave",
      startDate: "2026-04-24",
      endDate: "2026-04-26",
      duration: 3,
      reason: "Recovery period after an outpatient procedure.",
      status: "Pending",
      approver: "People Operations Lead",
    },
    {
      id: 3,
      employeeId: "EMP-019",
      name: "Aung Ko Oo",
      department: "IT",
      role: "Mobile Developer",
      type: "Casual Leave",
      startDate: "2026-04-28",
      endDate: "2026-04-28",
      duration: 1,
      reason: "Personal appointment outside office hours.",
      status: "Approved",
      approver: "Engineering Manager",
    },
    {
      id: 4,
      employeeId: "EMP-011",
      name: "Nandar Oo",
      department: "Marketing",
      role: "Content Creator",
      type: "Work From Home",
      startDate: "2026-04-30",
      endDate: "2026-05-02",
      duration: 3,
      reason: "Remote support for a regional campaign launch.",
      status: "Pending",
      approver: "Marketing Lead",
    },
    {
      id: 5,
      employeeId: "EMP-020",
      name: "Khin Thazin",
      department: "HR",
      role: "Training Coordinator",
      type: "Annual Leave",
      startDate: "2026-04-18",
      endDate: "2026-04-22",
      duration: 5,
      reason: "Scheduled personal leave after quarterly workshops.",
      status: "Rejected",
      approver: "HR Manager",
    },
    {
      id: 6,
      employeeId: "EMP-006",
      name: "Zaw Min Tun",
      department: "IT",
      role: "Backend Developer",
      type: "Emergency Leave",
      startDate: "2026-04-24",
      endDate: "2026-04-25",
      duration: 2,
      reason: "Urgent family matter requiring immediate travel.",
      status: "Approved",
      approver: "Engineering Manager",
    },
  ];
  return { leaves };
}
